### ISSUE TITLE
怎么播放在线音频文件？

### ISSUE THREAD

**Issue by GuangNian10000** [IAmWilling/MediaPlayerServer#1]

**Comment by IAmWilling** [comment]
MediaManager.playList(item:PlaylistItem,playIndex:Int = 0)
也可以实现 playlistitem接口，填写播放地址即可转换成list调用该函数

**Comment by IAmWilling** [comment]
@GuangNian10000

**Comment by GuangNian10000** [comment]
感谢回复，现在可以了。谢谢
不过还有另外一个问题，怎么更新播放列表中的数据？。setMediaItem会清除播放列表，添加指定的MediaItem并将位置重置为默认位置。
我希望像adapter一样可以更新数据。

**Comment by IAmWilling** [comment]
有一个监听音频改变的接口，当音频改变后再做adapter更新

**Comment by IAmWilling** [comment]
> 谢谢回复，现在可以了。谢谢 还有一个问题，怎么更新播放列表中的数据？。setMediaItem 会清除播放列表，添加指定的MediaItem 位置显示为默认位置。 我希望像适配器一样可以更新数据。

有一个监听音频的声音，当音频播放后做适配器更新

**Comment by IAmWilling** [comment]
> 有一个监听音频改变的接口，当音频改变后再做adapter更新

有一个监听音频改变的接口，当音频改变后再做adapter更新

**Comment by IAmWilling** [comment]
> 谢谢回复，现在可以了。谢谢 还有一个问题，怎么更新播放列表中的数据？。setMediaItem 会清除播放列表，添加指定的MediaItem 位置显示为默认位置。 我希望像适配器一样可以更新数据。
有一个监听音频改变的接口，当音频改变后再做adapter更新

**Comment by IAmWilling** [comment]
> 谢谢回复，现在可以了。谢谢 还有一个问题，怎么更新播放列表中的数据？。setMediaItem 会清除播放列表，添加指定的MediaItem 位置显示为默认位置。 我希望像适配器一样可以更新数据。

有一个监听音频改变的接口，当音频改变后再做adapter更新

**Comment by IAmWilling** [comment]
> 谢谢回复，现在可以了。谢谢 还有一个问题，怎么更新播放列表中的数据？。setMediaItem 会清除播放列表，添加指定的MediaItem 位置显示为默认位置。 我希望像适配器一样可以更新数据。

再点击adapter播放媒体的时候，可以用playlist方法重新设置一遍，playerlist有一个参数是设置播放index

**Comment by GuangNian10000** [comment]
我的场景是初始化列表的时候url都是空的，url 不是一次全部请求下来的，是播的时候请求上一首、当前、下一首的url，所以再播放的时候，我会在后台请求相应的地址然后再更新列表中的url。
playerlist会再调用一次播放，然后playerlist中调用了setMediaItems而这个方法，但是他里面是先清空列表后再自动从头开始播，这样会影响当前播放的音频，我想的只是改变数据，不做任何操作。不过我看到setMediaItems这个方法可以传个flase就好了，看了下描述并不知道为啥会解决这个问题。。不过确实他不会再调一次播放了：
注释如下：
  清除播放列表并添加指定的MediaItems。
  参数:
  mediaItems——新的mediaItems。
  resetPosition -播放位置是否应该重置到第一个Timeline.Window的默认位置。如果为false，播放将从getCurrentWindowIndex()和getCurrentPosition()定义的位置开始。
我用的是最新版本2.17

**Comment by IAmWilling** [comment]
> 我的场景是初始化列表的时候url都是空的，url 不是一次全部请求下来的，是播的时候请求上一首、当前、下一首的url，所以再播放的时候，我会在后台请求相应的地址然后再更新列表中的url。 playerlist会再调用一次播放，然后playerlist中调用了setMediaItems而这个方法，但是他里面是先清空列表后再自动从头开始播，这样会影响当前播放的音频，我想的只是改变数据，不做任何操作。不过我看到setMediaItems这个方法可以传个flase就好了，看了下描述并不知道为啥会解决这个问题。。不过确实他不会再调一次播放了： 注释如下： 清除播放列表并添加指定的MediaItems。 参数: mediaItems——新的mediaItems。 resetPosition -播放位置是否应该重置到第一个Timeline.Window的默认位置。如果为false，播放将从getCurrentWindowIndex()和getCurrentPosition()定义的位置开始。 我用的是最新版本2.17

我大概明白了 你不需要重新播放 只是要改变指定位置的url对吧？这样的话 我这里没有提供，需要的话可能要晚上更新一下，目前在getSimpleExoPlayer() 获取播放实例后，有一个方法 getMediaItemAt(playIndex).buildUpon().setUri(Uri.parse(你的Url))  这样你试一下

**Comment by GuangNian10000** [comment]
getMediaItemAt(playIndex).buildUpon().setUri(Uri.parse(你的Url)) 
设置了但是不起作用，应该要调用一下更新列表的方法么，但是我找不到

**Comment by GuangNian10000** [comment]
Sets the optional URI.
If uri is null or unset then no MediaItem.LocalConfiguration object is created during build() and no other Builder methods that would populate localConfiguration should be called.

这个方法不会改变localConfiguration中的url 而播放的时候就是用的这个地址

**Comment by GuangNian10000** [comment]
![image](https://user-images.githubusercontent.com/44353535/147028690-c0b04ed7-42bf-463c-800b-4f2cd3a74e23.png)
调用seturl后依然是“”

**Comment by IAmWilling** [comment]
> ![image](https://user-images.githubusercontent.com/44353535/147028690-c0b04ed7-42bf-463c-800b-4f2cd3a74e23.png) 调用seturl后依然是“”

增加了一个版本 1.0.2 可以更新一下 增加了三个api
说明：[https://github.com/IAmWilling/MediaPlayerServer/releases/tag/1.0.2](url)

**Comment by IAmWilling** [comment]
> ![image](https://user-images.githubusercontent.com/44353535/147028690-c0b04ed7-42bf-463c-800b-4f2cd3a74e23.png) 调用seturl后依然是“”

changeMediaItemAtUrl(index,url)  新增api 改变指定位置的url链接，不要改变当前正在播放的即可，确保index索引在playlist中列表的范围内

**Comment by IAmWilling** [comment]
@GuangNian10000  1.0.3         1.0.2tag有点问题

**Comment by GuangNian10000** [comment]
解决了，十分感谢
